"""Deployment artifact generation: Dockerfile, entrypoint, env template."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

_DOCKERFILE = """\
FROM python:3.12-slim

LABEL org.opencontainers.image.title="aire deployment"
LABEL org.opencontainers.image.description="Generated by the aire AI creation library"

WORKDIR /app
COPY requirements.lock /app/requirements.lock
RUN pip install --no-cache-dir -r requirements.lock

COPY . /app

EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=5s CMD python -c "import urllib.request;urllib.request.urlopen('http://localhost:8000/health')"

CMD ["uvicorn", "entrypoint:app", "--host", "0.0.0.0", "--port", "8000"]
"""

_ENTRYPOINT = """\
\"\"\"Generated by aire deploy. Serves the application defined in app.py.\"\"\"

from app import build_target  # user-provided: returns an Agent, Knowledge or Model

from aire.deployment import create_app

app = create_app(build_target())
"""

_ENV_TEMPLATE = """\
# Provider credentials (never commit real values)
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
HF_TOKEN=
OLLAMA_HOST=http://localhost:11434

# aire configuration overrides (AIRE_<section>__<key>)
AIRE_PROJECT={project}
AIRE_MODEL__REF=mock:echo
"""


class DeployArtifacts(BaseModel):
    """Files generated for a deployment."""

    directory: str
    files: list[str] = Field(default_factory=list)


def generate_artifacts(
    directory: str | Path,
    *,
    project: str = "aire-app",
    extra_requirements: list[str] | None = None,
) -> DeployArtifacts:
    """Write Dockerfile, entrypoint, env template and lock file to ``directory``."""
    target = Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    requirements = ["aire[serve]>=0.1.0", *(extra_requirements or [])]
    files: list[str] = []
    for name, content in {
        "Dockerfile": _DOCKERFILE,
        "entrypoint.py": _ENTRYPOINT,
        ".env.template": _ENV_TEMPLATE.format(project=project),
        "requirements.lock": "\n".join(requirements) + "\n",
    }.items():
        path = target / name
        path.write_text(content)
        files.append(str(path))
    return DeployArtifacts(directory=str(target), files=files)


def describe() -> dict[str, Any]:
    return {
        "kind": "deployment",
        "artifacts": ["Dockerfile", "entrypoint.py", ".env.template", "requirements.lock"],
        "endpoints": ["/health", "/ready", "/manifest", "/metrics"],
    }
